name: ci api

on:
  push:
    branches: [ master ]

jobs:
  push-docker-hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: natin56y/dice-town-api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: push-docker-hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 30m
          script: |
            curl https://gist.githubusercontent.com/anonymax25/8566e982dfdbe4ae5e28dc89886dee4b/raw > docker-compose.yml
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d


